name: bBot CI

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: |
          echo 'Building bBot Docker Image'
          export NAME='taranvohra/bbot'
          export TAG=`git log -1 --pretty=%h`
          export CURRENT="${NAME}:${TAG}"
          export LATEST="${NAME}:latest"
          docker build -t ${CURRENT} .
          docker tag ${CURRENT} ${LATEST}

      - name: Docker Login
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_PASSWORD

      - name: Docker Publish
        run: |
          docker push taranvohra/bbot
          echo 'Done ✅'
